spring:
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1
    alicloud:
      oss:
        endpoint: oss-cn-shenzhen.aliyuncs.com
      access-key:
      secret-key: 
      bucket-name: malldev
  application:
    name: mall-third-party

server:
  port: 13000
